triviaQuiz/config/routes.rb
Rails.application.routes.draw do
  get 'takequiz/takequiz'
  get 'scoreboard/scoreboard'
  
  root 'add_questions#index'

  resources :add_questions


end

triviaQuiz/app/models/add_question.rb
class AddQuestion
  include Mongoid::Document
  field :question, type: String
  field :correctOption1, type: String
  field :Option2, type: String
  field :Option3, type: String
end

triviaQuiz/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

triviaQuiz/app/controllers/add_questions_controller.rb
class AddQuestionsController < ApplicationController
  before_action :set_add_question, only: [:show, :edit, :update, :destroy]

  # GET /add_questions
  # GET /add_questions.json
  def index
    @add_questions = AddQuestion.all
  end

  # GET /add_questions/1
  # GET /add_questions/1.json
  def show
  end

  # GET /add_questions/new
  def new
    @add_question = AddQuestion.new
  end

  # GET /add_questions/1/edit
  def edit
  end

  # POST /add_questions
  # POST /add_questions.json
  def create
    @add_question = AddQuestion.new(add_question_params)

    respond_to do |format|
      if @add_question.save
        format.html { redirect_to @add_question, notice: 'Add question was successfully created.' }
        format.json { render :show, status: :created, location: @add_question }
      else
        format.html { render :new }
        format.json { render json: @add_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /add_questions/1
  # PATCH/PUT /add_questions/1.json
  def update
    respond_to do |format|
      if @add_question.update(add_question_params)
        format.html { redirect_to @add_question, notice: 'Add question was successfully updated.' }
        format.json { render :show, status: :ok, location: @add_question }
      else
        format.html { render :edit }
        format.json { render json: @add_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /add_questions/1
  # DELETE /add_questions/1.json
  def destroy
    @add_question.destroy
    respond_to do |format|
      format.html { redirect_to add_questions_url, notice: 'Add question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_add_question
      @add_question = AddQuestion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def add_question_params
      params.require(:add_question).permit(:question, :correctOption1, :Option2, :Option3)
    end
end

triviaQuiz/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

triviaQuiz/app/helpers/add_questions_helper.rb
module AddQuestionsHelper
end

triviaQuiz/app/helpers/application_helper.rb
module ApplicationHelper
end

triviaQuiz/app/views/add_questions/_form.html.erb
<div class="container">
  <%= form_with(model: add_question, local: true) do |form| %>
    <% if add_question.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(add_question.errors.count, "error") %> prohibited this add_question from being saved:</h2>

        <ul>
          <% add_question.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :question %>
      <%= form.text_field :question %>
    </div>

    <div class="field">
      <%= form.label :correctOption1 %>
      <%= form.text_field :correctOption1 %>
    </div>

    <div class="field">
      <%= form.label :Option2 %>
      <%= form.text_field :Option2 %>
    </div>

    <div class="field">
      <%= form.label :Option3 %>
      <%= form.text_field :Option3 %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

</div>

triviaQuiz/app/views/add_questions/edit.html.erb
<div class="container">
  <h1>Editing Add Question</h1>

  <%= render 'form', add_question: @add_question %>

  <%= link_to 'Show', @add_question %> |
  <%= link_to 'Back', add_questions_path %>

</div>

triviaQuiz/app/views/add_questions/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Add Questions</h1>

<table style="width:100%">
  <thead>
    <tr>
      <th>Question</th>
      <th>Correctoption1</th>
      <th>Option2</th>
      <th>Option3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @add_questions.each do |add_question| %>
      <tr>
        <td><%= add_question.question %></td>
        <td><%= add_question.correctOption1 %></td>
        <td><%= add_question.Option2 %></td>
        <td><%= add_question.Option3 %></td>
        <td><%= link_to 'Show', add_question %></td>
        <td><%= link_to 'Edit', edit_add_question_path(add_question) %></td>
        <td><%= link_to 'Destroy', add_question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Add Question', new_add_question_path %>

</div>

triviaQuiz/app/views/add_questions/new.html.erb
<div class="container">

  <h1>New Add Question</h1>

  <%= render 'form', add_question: @add_question %>

  <%= link_to 'Back', add_questions_path %>

</div>

triviaQuiz/app/views/add_questions/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Question:</strong>
    <%= @add_question.question %>
  </p>

  <p>
    <strong>Correctoption1:</strong>
    <%= @add_question.correctOption1 %>
  </p>

  <p>
    <strong>Option2:</strong>
    <%= @add_question.Option2 %>
  </p>

  <p>
    <strong>Option3:</strong>
    <%= @add_question.Option3 %>
  </p>

  <%= link_to 'Edit', edit_add_question_path(@add_question) %> |
  <%= link_to 'Back', add_questions_path %>

</div>

triviaQuiz/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>



<head>
  <title>Shadowhealthtrivia</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Shadow Health Trivia Quiz</title>
  <!-- Bootstrap -->
  <link href="/css/bootstrap.min.css" rel="stylesheet">
  <style>
    .navbar{
      margin-bottom:0;
      border-radius:0;
    }
  </style>
</head>


<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/takequiz/takequiz">Shadow Health Trivia Quiz</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><a href="/takequiz/takequiz">Take Health Quiz<span class="sr-only">(current)</span></a></li>


        <li><%= link_to 'Back', add_questions_path %></li>

        <li class="active"><a href="/scoreboard/scoreboard">Score Boards</a></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->



</nav>
<!-- JUMBOTRON -->
<div class="jumbotron text-center">
  <div class="container">
    <h1>Welcome to Shadow Health Quiz</h1>
    <p>Learn !! Take Quiz !!  Be the top Scorer  !!</p>
    <!-- <a href="#" class="btn btn-primary">Read More</a> -->
  </div>
</div>
<%= yield %>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/js/bootstrap.min.js"></script>
</body>




</html>